# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QSplitter


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(708, 520)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tableView.setObjectName("tableView")
        self.verticalLayout_3.addWidget(self.tableView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.tableView_2 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_2.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tableView_2.setObjectName("tableView_2")
        self.verticalLayout_4.addWidget(self.tableView_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tableView_3 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_3.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tableView_3.setObjectName("tableView_3")
        self.verticalLayout_5.addWidget(self.tableView_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)

        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.tableView_5 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_5.setMaximumSize(QtCore.QSize(16777215, 400))
        self.tableView_5.setObjectName("tableView_5")
        self.verticalLayout_6.addWidget(self.tableView_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_6.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.tableView_4 = QtWidgets.QTableView(self.centralwidget)
        self.tableView_4.setObjectName("tableView_4")
        self.horizontalLayout_3.addWidget(self.tableView_4)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.widgetHead = QtWidgets.QWidget()
        self.widgetHead.setLayout(self.horizontalLayout_2)

        self.widgetBottom = QtWidgets.QWidget()
        self.widgetBottom.setLayout(self.horizontalLayout)

        self.splitter = QSplitter(Qt.Vertical)
        self.splitter.addWidget(self.widgetHead)
        self.splitter.addWidget(self.widgetBottom)
        self.verticalLayout.addWidget(self.splitter)


        self.input_box = QtWidgets.QTextEdit()
        self.input_box.setMinimumHeight(80)
        self.verticalLayout_6.addWidget(self.input_box)

        self.button = QtWidgets.QPushButton('Выполнить запрос')
        self.verticalLayout_6.addWidget(self.button)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("SQL Kovynev 6304", "MainWindow"))

        self.label.setText(_translate("MainWindow", "Таблица №1 - actor"))
        self.label_2.setText(_translate("MainWindow", "Таблица №2 - director"))
        self.label_3.setText(_translate("MainWindow", "Таблица №3 - movie"))
        self.label_7.setText(_translate("MainWindow", "Таблица №4 -  movie_x_actor"))

        self.label_4.setText(_translate("MainWindow", "Выберите запрос:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Запрос №1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Запрос №2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Запрос №3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Запрос №4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Запрос №5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Запрос №6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Запрос №7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Запрос №8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Запрос №9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Запрос №10"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Запрос №11"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Запрос №12"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Запрос №13"))
        self.comboBox.setItemText(13, _translate("MainWindow", "Запрос №14"))
        self.comboBox.setItemText(14, _translate("MainWindow", "Запрос №15"))
        self.label_5.setText(_translate("MainWindow", "Описание запроса:"))
        self.label_6.setText(_translate("MainWindow", "Этот запрос выполняет ..."))

        self.button.clicked.connect(MainWindow.query_to_db)
